name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      fail-fast: true

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
          cache: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.2.3"

      - name: Run acceptance and unit tests
        env:
          TF_ACC: true
          NJALLA_TESTACC_DOMAIN: ${{ secrets.NJALLA_TESTACC_DOMAIN }}
          NJALLA_API_TOKEN: ${{ secrets.NJALLA_API_TOKEN }}
        run: go test -v ./...

  release:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
